### ISSUE TITLE
Forge error on load

### ISSUE THREAD

**Issue by Lotwook** [AIE-Guild/AIE-Nomads-Modpack#102]
After upgrading to 1.2.3 I intermittently received this error. Now it's consistent and I can not load the game at all. Attached screenshot and log file of errors. 

![forge error](https://cloud.githubusercontent.com/assets/12598605/12279558/da44cd40-b955-11e5-85a0-26fc73a651b3.jpg)

[fml-client-latest_log.txt](https://github.com/AIE-Guild/AIE-Nomads-Modpack/files/88107/fml-client-latest_log.txt)

**Comment by mrogaski** [comment]
You should be running forge-10.13.4.1566, but it looks like you have forge-10.13.3.1448.

**Comment by Mementh** [comment]
yeah it has a issue running the newest version and something about the directory I had to fix if you run from a alternate location like i do.. 

before it allowed a newer version to be used without issue.. i bet there is some conflict now?

**Comment by mrogaski** [comment]
Fixed in https://github.com/AIE-Guild/AIE-Nomads-Modpack/commit/d011a849bf9ea4590e0d7b5ab9683b3445ef2785.
