### ISSUE TITLE
Request: Steve's Workshop

### ISSUE THREAD

**Issue by garlicinyoureye** [AIE-Guild/AIE-Nomads-Modpack#69]
I apologize if I'm posting this in the wrong place.  Would it be possible to add Steve's workshop mod to the pack?  The closest thing I've found to it is the Forestry Worktable without having a lot of crafting benches all over the place.

**Comment by mrogaski** [comment]
I don't see a problem with adding this.

**Comment by Mementh** [comment]
have heard good thigns about this.. allows some simple crafting automated :)
