### ISSUE TITLE
mekanism smelter does not have glass anymore

### ISSUE THREAD

**Issue by Mementh** [AIE-Guild/AIE-Nomads-Modpack#72]
found this out today while makign things.. the glass recipie has dissappeared from the energetic smelter when it was there before :/

**Comment by mrogaski** [comment]
What specific recipe are you referring to?

**Comment by Mementh** [comment]
I craft sand in my AE system ( cobble goes to a pulverizer) then put it to a energetic smelter.. but it was not coming out right.. was getting stuck in the auto ore converter ( did not have a setting for glass so it should have just passed through) 
i could pull it out of the ore converter (the energetic smelter was just "eating" the sand and just making 1 glass) and could not place it down.. or put it in the AE system but it was staying in my inventory after a relog

it seems to not be happening now.. if it happens again i will post
