### ISSUE TITLE
Add Mod: Inventory Tweaks

### ISSUE THREAD

**Issue by Jehdai** [AIE-Guild/AIE-Nomads-Modpack#9]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288184-inventory-tweaks-1-59-march-31

http://www.curse.com/mc-mods/minecraft/223094-inventory-tweaks

MIT 

this is the version we want (mirror listed on MCF post): http://build.technicpack.net/job/Inventory-Tweaks/147/artifact/build/libs/InventoryTweaks-1.58-147.jar

**Comment by mrogaski** [comment]
Good idea.
